name: React App Deploy to EB

on:
 push:
  branches: [main]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with: 
      node-version: '18'

   - name: Build with npm
     run: npm run build
